service: jamesandstefano
runtime: go111

handlers:
  - url: /rsvp
    script: auto
  - url: /savethedate/images
    static_dir: images
  - url: /savethedate/main\.js
    static_files: main.js
    upload: main\.js
    mime_type: application/javascript; charset=utf-8
  - url: /savethedate/([\w-]+)$
    static_files: savethedate/\1.html
    upload: savethedate/(.*)\.html
    mime_type: text/html; charset=utf-8
  - url: /.*
    static_files: index.html
    upload: index.html
    mime_type: text/html; charset=utf-8

error_handlers:
  - file: index.html

includes:
  - secrets.yaml
